Repository HullSeals/HalpyBOT, pull requests merged in 2023-02, with the labels that each got.

#317 Mitigate one of pydantic's thorns
  halpybot/halpyconfig.py
  halpybot/packages/ircclient/halpybot.py
Labels: bug

#313 [Halpy-311] Add Optional Module Fuses
  .env.template
  halpybot/commands/manual_case.py
  halpybot/commands/misc.py
  halpybot/halpyconfig.py
  halpybot/packages/checks/checks.py
  halpybot/packages/ircclient/halpybot.py
Labels: enhancement

#322 [Cleanup] Remove Unused get_time_seconds function
  halpybot/packages/utils/__init__.py
  halpybot/packages/utils/utils.py
  tests/test_utils.py
Labels: code review

#323 [Halpy-302] Create the Board Class
  CLI/DSSAUpdater/__main__.py
  data/help/commands.json
  halpybot/commands/__init__.py
  halpybot/commands/debug.py
  halpybot/commands/fact.py
  halpybot/commands/manual_case.py
  halpybot/commands/misc.py
  halpybot/commands/notify.py
  halpybot/commands/time.py
  halpybot/packages/board/__init__.py
  halpybot/packages/board/board.py
  halpybot/packages/ircclient/halpybot.py
  halpybot/server/server.py
  pyproject.toml
Labels: enhancement, feature, sacm
