Repository HullSeals/HalpyBOT, pull requests merged in 2023-01, with the labels that each got.

#301 [Fix] Various post-config overhaul fixes
  .env.template
  .github/workflows/black.yml
  .gitignore
  CLI/BackupFactUpdater/README.md
  CLI/DSSAUpdater/README.md
  CLI/DSSAUpdater/src/scraper.py
  CLI/EDDBFormatter/README.md
  CONTRIBUTING.md
  README.md
  config/config_template.ini
  halpybot/commands/caseutils.py
  halpybot/commands/drill.py
  halpybot/commands/fact.py
  halpybot/commands/manual_case.py
  halpybot/commands/misc.py
  halpybot/commands/notify.py
  halpybot/commands/ping.py
  halpybot/commands/settings.py
  halpybot/commands/userinfo.py
  halpybot/halpyconfig.py
  halpybot/packages/announcer/announcer.py
  halpybot/packages/checks/checks.py
  halpybot/packages/command/commandhandler.py
  halpybot/packages/database/__init__.py
  halpybot/packages/database/connection.py
  halpybot/packages/edsm/edsm.py
  halpybot/packages/facts/__init__.py
  halpybot/packages/facts/facthandler.py
  halpybot/packages/ircclient/halpybot.py
  halpybot/packages/models/context.py
  halpybot/packages/models/user.py
  halpybot/packages/notify/notify.py
  halpybot/packages/seals/userinfo.py
  halpybot/packages/utils/utils.py
  halpybot/server/auth.py
  halpybot/server/rank_change.py
  halpybot/server/server_announcer.py
  pylint.txt
  pyproject.toml
  requirements.txt
  start.py
  tests/conftest.py
  tests/fixtures/mock_edsm.py
  tests/test_commands.py
  tests/test_config.py
  tests/test_database.py
  tests/test_edsm.py
  tests/test_facts.py
  tests/test_seals.py
  tests/test_server.py
Labels: bug

#305 [Halpy-304] Establish Source of Truth
  halpybot/commands/bot_help.py
  halpybot/commands/drill.py
  halpybot/commands/edsm.py
  halpybot/commands/fact.py
  halpybot/commands/forcejoin.py
  halpybot/commands/manual_case.py
  halpybot/commands/misc.py
  halpybot/commands/notify.py
  halpybot/commands/ping.py
  halpybot/commands/puppet.py
  halpybot/commands/settings.py
  halpybot/commands/userinfo.py
  halpybot/packages/__init__.py
  halpybot/packages/announcer/__init__.py
  halpybot/packages/announcer/announcer.py
  halpybot/packages/announcer/twitter.py
  halpybot/packages/command/commandhandler.py
  halpybot/packages/database/__init__.py
  halpybot/packages/database/connection.py
  halpybot/packages/facts/facthandler.py
  halpybot/packages/ircclient/halpybot.py
  tests/conftest.py
  tests/test_commands.py
  tests/test_database.py
  tests/test_edsm.py
  tests/test_facts.py
  tests/test_seals.py
  tests/test_utils.py
Labels: enhancement, code review

#314 [Halpy-310] Autoremoval of appended "SYSTEM"
  halpybot/packages/edsm/edsm.py
Labels: feature
