Repository HullSeals/HalpyBOT, pull requests merged in 2024-05, with the labels that each got.

#364 [Halpy-362] Add Admin command to combine multiple cases
  data/help/commands.json
  halpybot/commands/caseutils.py
Labels: feature

#363 [Halpy-361] Update multiple dispatch commands to be able to use caseIDs and co
  data/help/commands.json
  halpybot/commands/edsm.py
  halpybot/commands/spansh.py
  halpybot/halpyconfig.py
  halpybot/packages/models/edsm_classes.py
Labels: enhancement, feature

#365 [Enhancement] Add Silent Welcome Option
  data/help/commands.json
  halpybot/commands/caseutils.py
  pyproject.toml
Labels: enhancement, dependencies
